version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  generate-config:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml

workflows:
  setup:
    jobs:
      - generate-config
