version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build
          command: echo "Build complete"

workflows:
  build-and-test:
    jobs:
      - build
